version: '3.8'

services:
  minimal-agent:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    environment:
      # Ollama settings (if using Ollama in another container)
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3:latest
      
      # OpenAI settings (set these in .env file)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      
      # DeepSeek settings (set these in .env file)
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - DEEPSEEK_URL=${DEEPSEEK_URL:-https://api.deepseek.com}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
    restart: unless-stopped

  # Optional: Ollama service for local LLM
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=5m
    restart: unless-stopped
    # Uncomment to enable GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama-data:
